### ISSUE TITLE
Incorrect documentation for pullsecrets as of CF206

### ISSUE THREAD

**Issue by DanieleVistalli** [HCL-TECH-SOFTWARE/digital-experience#29]
https://github.com/HCL-TECH-SOFTWARE/digital-experience/blob/181d35f06af935f92f62be11c8a823a24ce7182f/docs/deployment/install/container/helm_deployment/preparation/optional_tasks/optional_imagepullsecrets.md?plain=1#L17

Documentation suggets using:

```yaml
images:
  imagePullSecrets: 
  - name: "secretname"
```

this fails when appied to template.

The working syntax for CF206 is

```yaml
images:
  imagePullSecrets: 
  - "secretname"
```
